### ISSUE TITLE
Support for Heroes of the Storm?

### ISSUE THREAD

**Issue by mavrick** [benweier/battlenet-api#16]
Is there any plans or is it possible to add support for HotS?

Cheers

**Comment by benweier** [comment]
Hi @mavrick I absolutely plan to support HotS and HS when those APIs are made available! Unfortunately the docs haven't been updated yet so we just need to be patient (unless someone knows where some info has been posted)

**Comment by mavrick** [comment]
No worries dude, thanks for the update. I've signed up to the bnet api so will get an update as soon as they release it.

For now, we waits >_<

**Comment by mavrick** [comment]
... and wait.

**Comment by benweier** [comment]
Still waiting... there's whispers over at the Developer Forums that new APIs are coming Soon<sup>TM</sup> but not sure which or when.

`battlenet-api` has been deprecated and will no longer maintained. A ground-up rewrite is available at [blizzard.js](https://github.com/benweier/blizzard.js) featuring a major version number, a cleaner API, promises support, a test suite, richer documentation, and an example app.
