### ISSUE TITLE
Character API missing Profession infos

### ISSUE THREAD

**Issue by Firnael** [benweier/battlenet-api#20]
Hi,
Blizzard updated their API; added the "Professions" section to "Character".
Do you plan on updating your work ?

I guess it's just adding (in character.js)
`professions: function() {
      var args = battlenet.args.apply(null, arguments);
      args.params.fields = ['professions'];
      character(args.params, args.config, args.callback);
    },`

Thank you for your time, hope you're still working on it !
Cheers

**Comment by benweier** [comment]
Thanks for letting me know @Firnael. I'll update this as soon as I can

**Comment by benweier** [comment]
Resolved in version 0.12.0
