### ISSUE TITLE
Plans to support promises?

### ISSUE THREAD

**Issue by rejas** [benweier/battlenet-api#22]
Hi there, first: thanks for your library, using it now for my wow-rss-feed generator. But having callbacks is not always nice, so what are your thoughts on switching to a promise based approach?
Cheers, V

**Comment by benweier** [comment]
Hi @rejas I'm glad you find it useful! I've started a rewrite for v1.0.0 that will support Promises as well as callbacks. I'm still undecided whether I keep the `bnet.wow.character.achievements({...})` approach but I'm leaning towards something like `bnet.wow.character('achievements', {...})` instead.

**Comment by rejas** [comment]
Nice to hear that. As for changing the api calls: I don't mind changing those in my app when switching over to promises (and going to a v1.0.0 too), whatever you think is more maintainable and clean.
