### ISSUE TITLE
Typo in property name - "data.characterAchievements"

### ISSUE THREAD

**Issue by zuren** [benweier/battlenet-api#6]
Hey, great project!

There's a typo in `wow.data`. What's documented as "characterAchievement**s**" is actually `characterAchievement`.

I'd suggest adding the "s" to the function in `lib/wow/data.js` and a `characterAchievement` alias for API compatibility.

This is the first issue I've posted, so sorry if I've missed some etiquette!

**Comment by benweier** [comment]
Thanks @zuren, nice catch. Your issue description is perfect too

I'll make an update later today when I have a few minutes.

**Comment by zuren** [comment]
Thanks, I appreciate it. Have a good one.

**Comment by benweier** [comment]
I've fixed this in 0.8.4 and opted to not include an alias because I'm a terrible person who doesn't mind breaking a few things on the path to v1.0
