### ISSUE TITLE
bnet.account.id (etc.) cause "args is not defined" in users.js

### ISSUE THREAD

**Issue by kafoso** [benweier/battlenet-api#8]
The following fails using parameter with require, i.e.:
```javascript
var bnet = require('battlenet-api')(your_api_key);
```
- `bnet.account.id`
- `bnet.account.battletag`
- `bnet.account.wow`
- `bnet.account.sc2`

... as per examples here: https://github.com/benweier/battlenet-api#user-id

The `args` variable in users.js (https://github.com/benweier/battlenet-api/blob/7946806b9811c4729879665136996128bdbce655/lib/account/user.js#L9) has not been initalized. Should lines 9 through 11 even be there?

- Perhaps an overlook from this issue: https://github.com/benweier/battlenet-api/issues/3
- Perhaps it should be `battlenet.args`?

**Comment by benweier** [comment]
Thanks @kafoso :)

**Comment by kafoso** [comment]
No problem, but the issue is still not solved. You left another undefined `args` variable at the next line: https://github.com/benweier/battlenet-api/commit/ef243dc10a274b6ba27208e6495f92c12cc05373#diff-d8ab9bbcf935977cbec9505d9b45494eR10
